[package]
name = "bin-obfuscator"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
goblin = "0.8"
anyhow = "1.0"
iced-x86 = { version = "1.21.0", features = ["code_asm"] }
