[package]
name = "bin-obfuscator"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common", package = "bin-obfuscator-common" }
core = { path = "../core", package = "bin-obfuscator-core" }
clap = { version = "4.5", features = ["derive"] }
log = "0.4"