name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-audit
      run: cargo install cargo-audit
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run cargo fmt
      run: cargo fmt --check
    - name: Run cargo clippy
      run: cargo clippy --verbose
    - name: Run cargo audit
      run: cargo audit
